### ISSUE TITLE
Is this extension abandoned?

### ISSUE THREAD

**Issue by saeohioalpha** [devvcat/ssms-executor#10]
Is this extension abandoned? Will it be updated to work with the latest 17.x/18.x versions of SSMS?

Attached is the activity log with loading errors for extension on SSMSv17.9.1

[ActivityLog.txt](https://github.com/devvcat/ssms-executor/files/3085456/ActivityLog.txt)

**Comment by devvcat** [comment]
Hi @saeohioalpha, it's in my todo list to upgrade the extension for SSMS 18.

**Comment by saeohioalpha** [comment]
Thats good to hear!

**Comment by win32nipuh** [comment]
It works in SSMS2018.

**Comment by shadowjig** [comment]
> It works in SSMS2018.

What steps did you follow to get this working in SSMS 2018?  I'm assuming this is SSMS v18.x?

**Comment by win32nipuh** [comment]
Yes, it is SSMS 18.1 Release. I will check it again to remind ;-) and let you know little bit later

**Comment by shadowjig** [comment]
> Yes, it is SSMS 18.1 Release. I will check it again to remind ;-) and let you know little bit later

Where you able to find the steps you took to install this extension into SSMS 18?

**Comment by CurbedLarry** [comment]
Solution for 18.x is to copy the **SSMSExecutor** folder to:

C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Extensions\

But it appears broken on **Windows 7**

With respect to the developer this extension is amazing but a total disaster to install, and badly lacking testing and up-to-date documentation.

_EDIT: Corrected install folder_

**Comment by dtosti** [comment]
> Solution for 18.x is to copy the **SSMSExecutor** folder to:

Did @devvcat provide the solution you applied?

**Comment by CurbedLarry** [comment]
> Did @devvcat provide the solution you applied?

No, I think I found the solution with guesswork and StackOverflow comments. My frustration above was the fact I wasted many hours trying other fixes for Windows 7 without luck.

**Comment by devvcat** [comment]
Hi @CurbedLarry , @dtosti , @shadowjig , @win32nipuh , @saeohioalpha ,
just updated the installer. An option for SSMS 18.x (2019) was added.

**Comment by CurbedLarry** [comment]
> Hi @CurbedLarry , @dtosti , @shadowjig , @win32nipuh , @saeohioalpha ,
> just updated the installer. An option for SSMS 18.x (2019) was added.

Thank you @devvcat installer works well for 18.x and Wiki shows correct directory.

Still have the issue with SSMS 2014, appears installed but button is grey and shortcut does not work.

**Comment by dtosti** [comment]
> Thank you @devvcat installer works well for 18.x and Wiki shows correct directory.

I can confirm this. It works on 18.4.
