### ISSUE TITLE
Bug in wiki: SSMS v19.4 instructions not present

### ISSUE THREAD

**Issue by dtosti** [devvcat/ssms-executor#12]
The wiki does not provide any installation instructions for SSMS v19.

**Comment by devvcat** [comment]
Hi @dtosti ,

you probably mean SSMS v18.x, as it is the latest one. I've just updated the wiki page and released v2.0.3 that adds support for SSMS 18.x (2019)

**Comment by dtosti** [comment]
> Hi @dtosti ,
> 
> you probably mean SSMS v18.x, as it is the latest one. I've just updated the wiki page and released v2.0.3 that adds support for SSMS 18.x (2019)

yes @devvcat, you're right, it was a typo. 

I have installed v2.0.3 according to the wiki instructions and it worked. 

I am closing this issue as solved.
