### ISSUE TITLE
Difference between ExecuteStatement and ExecuteInnerStatement

### ISSUE THREAD

**Issue by manngo** [devvcat/ssms-executor#15]
What is the difference between ExecuteStatement and ExecuteInnerStatement ? They both seem to run a single statement, which is what I want, but I can’t see how they differ.

Thanks for a brilliant extension.

**Comment by devvcat** [comment]
With `ExecuteInnerStatement` the result will be the second select statement.
With `ExecuteStatement` the result will be all three statements. 

```sql
BEGIN
  SELECT 1
  SELECT 2 -- cursor is on this line
  SELECT 3
END
```

**Comment by manngo** [comment]
I didn’t know you could do that. Thanks.
