### ISSUE TITLE
Installing without the installer.

### ISSUE THREAD

**Issue by manngo** [devvcat/ssms-executor#17]
I do a lot of teaching on SSMS, so thank you so much for this extension.

Much of the teaching is remote, and in many cases the participants are on company machines which won’t allows downloading and running executables.

I know there is an accompanying ZIP file, and the idea is to extract it and copy to the `Extensions` folder. However, after I install using the installer, the `Extensions` folder only has a single `SSMSExecutor` folder with only two files `extension.vsixmanifest` and `SSMSExecutor.pkgdef`.

What happens with the other files?

**Comment by devvcat** [comment]
Hi @manngo,
the file `SSMSExecutor.pkgdef` defines the location for the other files. Open it in `notepad` and check the field `"CodeBase"="<path>\SSMSExecutor.dll"`.

The ZIP file, has it configured to look in the 'package' folder (the folder that has the extension).
`"CodeBase"="$PackageFolder$\SSMSExecutor.dll"`

Glad that the extension is useful for you.

**Comment by manngo** [comment]
Thanks. So, if I understand correctly, all of the files are indeed installed, but not necessarily in the same place. The `SSMSExecutor.pkgdef` file indicates. where.
