### ISSUE TITLE
Is there a way of installing this exenstion in a non-privileged location?

### ISSUE THREAD

**Issue by manngo** [devvcat/ssms-executor#18]
Many of my students are using a work computer where IT has the impression that you shouldn’t be allows to touch it.

As far as I can see, saving the unzipped extension in the `Extensions` folder required Admin privileges, which is a little like asking the Pope for the keys to the Vatican.

I have now idea how the SSMS extension mechanism works, but is there any chance of running this extension from another location, such as the user’s home directory?

**Comment by devvcat** [comment]
I don't believe (or not aware) that SSMS looks for extensions in location outside the SSMS' installation folder (by default `C:\Program Files (x86)\Microsoft SQL Server Management Studio 1x`). So, if SSMS is installed in an unprivileged folder, extensions can be installed without an admin account.

Note: in SSMS 2012, it was possible to install extensions in the `%APPDATA%` folder; however it doesn't work in SSMS 18/19.
