### ISSUE TITLE
Requirements for recompiling the project?

### ISSUE THREAD

**Issue by delphym** [devvcat/ssms-executor#19]
Hi there, this extension to MSSMS is promising, but with my version to be 18.12.x  I'm hitting the hard space, as the shortcut is not available, respectively it triggers 'Resource View'.

reading the Known Issues -> Hardcoded key binding
I'd like to know what do I need to have to be able to recompile the project.
(I'm coming from Java background on POSIX systems, where if needed, I had all dev tools available, but on Windows, I'm getting lost).

Many thanks in advance.

**Comment by devvcat** [comment]
Hi @delphym ,

the key binding is no longer hardcodded. The shortcuts can be changed from `Tools/Options/Keyboard`
Search for commands:

```
Tools.ExecuteStatement
Tools.ExecuteInnerStatement

```

As for recompiling the project. You need the latest `Visual Studio` (Community version) with the `Visual Studio extension development` workload installed.
Alongside you also need the SSMS installed on the same machine.

When you open the project (in properties) you should change the folder where to store the extension while developing.
For SSMS v18 the path usually is `C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions\SSMSExecutor`

You can verify the above path from the registry key `Computer\HKEY_CURRENT_USER\Software\Microsoft\SQL Server Management Studio\18.0_IsoShell_Config\InstallDir`



Sorry for the late response!
