### ISSUE TITLE
Always performs F5

### ISSUE THREAD

**Issue by oo777** [devvcat/ssms-executor#3]
Great Idea but doesnt work for me. x86 Win7, SSMS 2014, installations was fine but hittin ctrl+shift+e always performs a F5 executing the whole script. Do you interpret the GO statement or you just interpret the current line?
I would prefer a ctrl-enter to run the current statement if you have to switch from oracle to microsoft.

**Comment by devvcat** [comment]
Hi @oo777, 
*GO* is not a Transact-SQL statement; it is a command recognized by the *sqlcmd* and *osql* utilities and SQL Server Management Studio Code editor.
Even you can change the literal in *Query Options*.
As such I don't treat it as statement separator.

If you have query with *GO* commands, the whole query is one statement.
```
select top 1 * 
from data_load_error
go
select top 2 * 
from data_load_error
go
select top 3 * 
from data_load_error
go
select top 4 * 
from data_load_error
go
```

However, if your query don't have GO commands, each statement will be executed individually based on the position of the caret (each statement can span multiple lines).
```
select top 1 * 
from data_load_error

select top 2 * 
from data_load_error -- Caret within this statement, only this one will be executed

select top 3 * 
from data_load_error

select top 4 * 
from data_load_error
```

Unfortunately, the keyboard combination is hardcoded for SSMS 2014/16. I don't know how to dynamically change it and add a setting in the Options, yet.

In the AddIn for SSMS 2012 you can change the shortcut as you desire.

Thank you,
Stanislav

**Comment by oo777** [comment]
Got it, thanks!
