### ISSUE TITLE
Add verification instructions and changing key mapping

### ISSUE THREAD

**Issue by pgensler** [devvcat/ssms-executor#5]
Do you accept PR's, or is this under heavy development now? I was hoping to add some information around verifying the plugin was added correctly, and how to change the keys mapped, if this user desires. Thanks.

**Comment by devvcat** [comment]
Hi @pgensler, any PRs are welcome.

As for the key mapping, in the latest release `v2.0.2-alpha` you can now change the shortcuts from `Tools/ Options/ Keyboard`
